version: "3.8"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=fibotree
      - POSTGRESQL_PASSWORD=fibotree_password
      - POSTGRESQL_DATABASE=publiz

volumes:
  postgresql_data: {}
